.github/workflows/deploy.yml
close #2 
CI/CD 구현을 위한 github actions의 workflow를 생성하였습니다.
- application.yml이 github상에 올라가지 않는 관계로 테스트 과정에서 build가 실패할 수 있습니다.
- 따라서 -x test를 통해 테스트를 생략하였습니다.
```yml
- name: Build with Gradle
run: ./gradlew clean bootJar -x test
```
- 서버에 존재하는 application.yml을 읽어 서버가 실행될 수 있도록 설정하였습니다.
```yml
- name: Restart service on server
run: |
ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
pkill -f 'java -jar' || true
nohup java -jar ${{ secrets.REMOTE_APP_PATH }}/app.jar \
--spring.config.location=file:${{ secrets.REMOTE_APP_PATH }}/application.yml \
--spring.profiles.active=prod \
> ${{ secrets.REMOTE_APP_PATH }}/app.log 2>&1 &
```
=> [CI] Add CI/CD workflow

.github/workflows/deploy.yml
close #2 
webfactory/ssh-agent 버전 수정
=> [CI] fix CI/CD workflow

.github/workflows/deploy.yml
close #2 
webfactory/ssh-agent@v0.9.0 버전 수정
=> [CI/CD] workflow 수정

src/main/java/likelion/scent_yonsei/domain/foodBooth/api/controller/FoodBoothController.java
sample api 생성을 통해 github action 동작을 검증하고자 합니다.
=> [FEAT] sample api 생성

src/main/java/likelion/scent_yonsei/makers/api/controller/ReviewController.java, src/main/java/likelion/scent_yonsei/makers/api/dto/ReviewReq.java, src/main/java/likelion/scent_yonsei/makers/api/service/ReviewService.java, src/main/java/likelion/scent_yonsei/makers/core/Review.java, src/main/java/likelion/scent_yonsei/makers/core/ReviewRepository.java
=> [FEAT] review 받아오기

src/main/java/likelion/scent_yonsei/common/Response.java
close #15 
Response용 DTO를 생성해두었습니다
=> [FEAT] Response용 DTO 생성

src/main/java/likelion/scent_yonsei/domain/makers/api/controller/ReviewController.java, src/main/java/likelion/scent_yonsei/domain/makers/api/dto/ReviewRes.java, src/main/java/likelion/scent_yonsei/domain/makers/api/service/ReviewService.java
close #17 
- Response 클래스를 사용하여 response 형식을 통일하였습니다.
- @Transactional 어노테이션을 사용하였습니다.
=> [FIX] Review API 개선

.github/workflows/deploy.yml
close #22 
- CI/CD 빌드 파일 저장 경로를 수정하였습니다.
- application.yml 참조 위치를 수정하였습니다.
=> [MERGE] CI/CD 설정 변경

.github/workflows/deploy.yml
=> [CI/CD] github workflow 수정

.github/workflows/deploy.yml, src/main/java/likelion/scent_yonsei/domain/show/api/dto/ShowDetailRes.java, src/main/java/likelion/scent_yonsei/domain/show/api/dto/ShowRes.java, src/main/java/likelion/scent_yonsei/domain/show/api/service/ShowService.java, src/main/java/likelion/scent_yonsei/domain/show/core/Show.java, src/main/java/likelion/scent_yonsei/domain/show/core/ShowPhoto.java, src/main/java/likelion/scent_yonsei/domain/show/core/ShowPhotoRepository.java, src/main/java/likelion/scent_yonsei/domain/show/core/ShowRepository.java
close #
- 공연 정보 반환 API를 완성하여 main으로 합칩니다
=> [MERGE] 공연 정보 반환 API main으로 합치기

src/main/java/likelion/scent_yonsei/domain/booth/api/controller/BoothController.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothListDataDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothListResponseDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothSummaryDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/DetailResponseDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/FoodTruckDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/FoodTruckSummaryDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/IdErrorDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/MenuDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/SearchErrorDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java, src/main/java/likelion/scent_yonsei/domain/booth/core/Booth.java, src/main/java/likelion/scent_yonsei/domain/booth/core/BoothMenu.java, src/main/java/likelion/scent_yonsei/domain/booth/core/BoothPhoto.java, src/main/java/likelion/scent_yonsei/domain/booth/core/BoothRepository.java, src/main/java/likelion/scent_yonsei/domain/booth/core/FoodTruck.java, src/main/java/likelion/scent_yonsei/domain/booth/core/FoodTruckRepository.java, src/main/java/likelion/scent_yonsei/domain/booth/core/TruckMenu.java
close #11 
부스 목록 및 세부 정보 반환 api 제작
=> [FEAT] booth 목록 및 세부정보 반환

src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java, src/main/java/likelion/scent_yonsei/domain/booth/core/Booth.java, src/main/java/likelion/scent_yonsei/domain/booth/core/FoodTruck.java
close #33
Booth, FoodTruck table nullable 수정
=> [FIX] booth 정보 nullable 수정

src/main/java/likelion/scent_yonsei/domain/show/api/service/ShowService.java, src/main/java/likelion/scent_yonsei/domain/show/core/ShowPhoto.java
close #
- shows 테이블 column명을 실제 DB에 맞도록 수정하였습니다.
=> [FIX] shows 테이블 column명 수정

src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java
close #39 
booth 상세조회 시 사진 리스트를 반환
BoothDetailDto
BoothService
=> [FEAT] booth 상세조회 사진 리스트 반환

src/main/java/likelion/scent_yonsei/domain/booth/api/dto/FoodTruckDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java, src/main/java/likelion/scent_yonsei/domain/booth/core/FoodTruck.java
close #44 
푸드트럭 정보 반환 시 photo도 반환합니다. (사진 1장 반환)
=> [FEAT] 푸드트럭 photo 반환 추가

src/main/java/likelion/scent_yonsei/domain/booth/api/dto/FoodTruckDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java, src/main/java/likelion/scent_yonsei/domain/booth/core/FoodTruck.java, src/main/java/likelion/scent_yonsei/domain/notice/api/controller/NoticeController.java
close #
- 푸드트럭 api 사진반환이 필요한 점을 수정하였습니다.
=> [MERGE] 푸드트럭 api 사진반환 수정

.github/workflows/deploy.yml
close #
- 2개 서버로 변경사항을 자동으로 배포하는 github action을 구현하였습니다.
=> [CI/CD] github action 수정

.github/workflows/deploy.yml
close #
- github action 코드를 수정합니다.
=> [fix] github action 수정

src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/FoodTruckDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/MenuDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java, src/main/java/likelion/scent_yonsei/domain/booth/core/Booth.java
close #49 
부스 상세정보 반환 시 menu_photo, section, location 추가
=> [FEAT] 부스 상세정보 반환 시 menu_photo, section, location 추가

.github/workflows/deploy.yml, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/BoothDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/FoodTruckDetailDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/dto/MenuDto.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java, src/main/java/likelion/scent_yonsei/domain/booth/core/Booth.java
close #
- 부스 api에서 section, location을 추가로 반환
- location을 String형으로 변경
=> [MERGE] 부스 api 수정

src/main/java/likelion/scent_yonsei/domain/booth/api/controller/BoothController.java, src/main/java/likelion/scent_yonsei/domain/booth/api/service/BoothService.java
close #
- booth api 수정사항 반영하였습니다.
=> [MERGE] booth api 수정사항 반영

src/main/java/likelion/scent_yonsei/domain/booth/core/BoothMenu.java
=> [FIX] fix length of menu name

build.gradle
close #
- ALB 사용(health check)을 위해 aurator를 build.gradle에 추가합니다
=> [SETTING] ALB setting

src/main/java/likelion/scent_yonsei/domain/booth/api/dto/MenuDto.java, src/main/java/likelion/scent_yonsei/domain/booth/core/BoothMenu.java, src/main/java/likelion/scent_yonsei/domain/booth/core/TruckMenu.java
close #58 
메뉴 가격 null 허용
MenuDto
BoothMenu
TruckMenu
=> menu 가격 null 허용
